baseURL = "www.example.com"
defaultContentLanguage = "pt-br"
themesDir = "themes"
theme = "hyde-hyde"
author = "Tet"
pluralizeListTitles = false

[params]
author = "Tet"
mainSections = "posts"
description = "Descrição no idioma settado em defaultContentLanguage"

relatedPosts = true

[languages]
  [languages.pt-br]
    languageName = "Português do Brasil"
    weight = 5
  [languages.en]
    description  = "Description text in the sidebar in English"
    languageName = "English"
    weight = 10 

[languages.pt-br.Menus]
      main = [
    { Name = "Posts", URL = "/", weight = 5 },
    { Name = "Sobre Mim", URL = "/about/", weight = 10 },
    { Name = "Versão em Inglês", URL = "/en", weight = 100 }
    ]


[languages.en.Menus]
      main = [
    { Name = "Posts", URL = "/en", weight = 5 },
    { Name = "About me", URL = "/en/about", weight = 10 },
    { Name = "Portuguese Version", URL = "/", weight = 100 }
  ]
