name = "j-hyde"
license = "MIT"
licenselink = "https://gitlab.com/jwaghetti/j-hyde/blob/master/LICENSE.md"
description = "hyde-hyde theme with some specifics"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio"]
homepage = "https://gitlab.com/jwaghetti/hyde-hyde"
min_version = "0.43"

[author]
    author =  "Jean Waghetti"
    repo = "https://gitlab.com/jwaghetti/j-hyde"

# If Porting existing theme
[original]
    name = "htr3n"
    homepage = "https://htr3n.github.io"
    repo = "https://github.com/htr3n/hyde-hyde"
